export enum ApiErrorCode {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  INVALID_REQUEST = "INVALID_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
};

export enum AuthErrorCode {
  MISSING_FIELDS = "MISSING_FIELDS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_CREATION_FAILED = "USER_CREATION_FAILED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
}

export enum ChatType {
  DIRECT = "DIRECT",
  GROUP = "GROUP",
}

export enum MemberRole {
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
}

export enum SocketEvent {
  CONNECTION = "connection",
  DISCONNECT = "disconnect",
  SEND_MESSAGE = "send_message",
  NEW_MESSAGE = "new_message",
  MESSAGE_TRANSLATED = "message_translated",
  JOIN_CHAT = "join_chat",
}
