export enum ApiErrorCode {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  INVALID_REQUEST = "INVALID_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
};

export enum AuthErrorCode {
  MISSING_FIELDS = "MISSING_FIELDS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_CREATION_FAILED = "USER_CREATION_FAILED",
}
